In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("https://raw.githubusercontent.com/PratikPhysics/SNDT-College/refs/heads/main/car_price_dataset.csv")
df

,Brand,Model,Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Price
0,Kia,Rio,2020,4.2,Diesel,Manual,289944,3,5,8501
1,Chevrolet,Malibu,2012,2.0,Hybrid,Automatic,5356,2,3,12092
2,Mercedes,GLA,2020,4.2,Diesel,Automatic,231440,4,2,11171
3,Audi,Q5,2023,2.0,Electric,Manual,160971,2,1,11780
4,Volkswagen,Golf,2003,2.6,Hybrid,Semi-Automatic,286618,3,3,2867
...,...,...,...,...,...,...,...,...,...,...
9995,Kia,Optima,2004,3.7,Diesel,Semi-Automatic,5794,2,4,8884
9996,Chevrolet,Impala,2002,1.4,Electric,Automatic,168000,2,1,6240
9997,BMW,3 Series,2010,3.0,Petrol,Automatic,86664,5,1,9866
9998,Ford,Explorer,2002,1.4,Hybrid,Automatic,225772,4,1,4084
9999,Volkswagen,Tiguan,2001,2.1,Diesel,Manual,157882,3,3,3342

In [4]:
# 1. What is the average price of all cars in the dataset?
print(f"The average price of all cars in the dataset is ${round(df['Price'].mean(),2)}")

The average price of all cars in the dataset is $8852.96

In [5]:
#2. Which car brand has the highest average price?

Brand =df[df["Price"] == df["Price"].max()]["Brand"][1100]

print(f"The brand with the highest price is {Brand}")

The brand with the highest price is Toyota

In [10]:
#3. What is the most common fuel type in the dataset?
fuel_type = df["Fuel_Type"].mode()[0]
print(f"The most common fuel type is {fuel_type}")

The most common fuel type is Electric

In [13]:
#4. How many cars have a mileage greater than 200,000?
mileage_greater_than_200000 = len(df[df["Mileage"] > 200000])
print(f"There are {mileage_greater_than_200000} cars with mileage greater than 200000")

There are 3290 cars with mileage greater than 200000

In [14]:
#5. What is the distribution of cars by transmission type?
print(df["Transmission"].value_counts())

Transmission
Manual            3372
Automatic         3317
Semi-Automatic    3311
Name: count, dtype: int64

In [21]:
#6. Which car model has the highest price?

print(df.loc[df["Price"].idxmax(), ["Brand", "Model", "Price"]])

Brand     Toyota
Model    Corolla
Price      18301
Name: 1100, dtype: object

In [24]:
#7. What is the average price of cars by fuel type?
print(df.groupby("Fuel_Type")["Price"].mean())

Fuel_Type
Diesel       8117.336385
Electric    10032.220190
Hybrid       9113.030167
Petrol       8070.561826
Name: Price, dtype: float64

In [26]:
#8. How many cars are from the year 2020 or later?
df[df["Year"] > 2020]

,Brand,Model,Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Price
3,Audi,Q5,2023,2.0,Electric,Manual,160971,2,1,11780
19,Mercedes,GLA,2021,1.5,Petrol,Manual,34640,2,1,11207
26,Audi,A3,2022,3.3,Electric,Manual,79350,5,3,14413
44,Audi,Q5,2023,3.6,Electric,Manual,238306,5,2,11833
51,Mercedes,GLA,2022,3.8,Diesel,Manual,191466,3,2,10670
...,...,...,...,...,...,...,...,...,...,...
9944,Honda,Civic,2021,2.6,Electric,Semi-Automatic,212430,5,4,10751
9970,Chevrolet,Impala,2022,1.1,Hybrid,Semi-Automatic,277974,4,2,7240
9973,Volkswagen,Tiguan,2021,3.7,Petrol,Semi-Automatic,156437,2,3,10971
9983,Mercedes,E-Class,2022,3.2,Petrol,Automatic,92823,5,4,13543
9984,Volkswagen,Passat,2023,3.0,Hybrid,Manual,290306,4,4,9193

In [28]:
#9. What is the average engine size for each brand?
print(df.groupby("Brand")["Engine_Size"].mean())

Brand
Audi          3.032948
BMW           2.976877
Chevrolet     2.993719
Ford          3.044275
Honda         2.925966
Hyundai       2.936683
Kia           3.053791
Mercedes      3.069745
Toyota        2.961443
Volkswagen    3.011078
Name: Engine_Size, dtype: float64

In [29]:
#10. Which car has the lowest mileage?
df.loc[df["Mileage"].idxmin()]

Brand                     Ford
Model                 Explorer
Year                      2006
Engine_Size                1.6
Fuel_Type             Electric
Transmission    Semi-Automatic
Mileage                     25
Doors                        3
Owner_Count                  2
Price                     9499
Name: 6824, dtype: object

In [30]:
#11. What is the correlation between mileage and price?
df["Mileage"].corr(df["Price"])

np.float64(-0.5512271827629014)

In [34]:
#12. How many cars have more than 2 owners?
(df["Owner_Count"] > 2).sum()

np.int64(5944)

In [35]:
#13. What is the average price of cars by year?
df.groupby("Year")["Price"].mean()

Year
2000     5393.735369
2001     5904.064039
2002     5956.751082
2003     6225.834646
2004     6330.725888
2005     6943.037123
2006     7249.961446
2007     7632.513953
2008     7728.418848
2009     8083.917293
2010     8503.419954
2011     8622.855234
2012     9011.446224
2013     9114.208531
2014     9587.455635
2015     9896.774648
2016    10177.600000
2017    10343.757506
2018    10939.192941
2019    11132.722090
2020    11495.284337
2021    11637.813299
2022    12067.690176
2023    12169.470982
Name: Price, dtype: float64

In [37]:
#14. Which car has the highest number of doors?
df[df["Doors"] == df["Doors"].max()]

,Brand,Model,Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Price
14,Volkswagen,Golf,2003,2.4,Petrol,Automatic,145921,5,2,5981
16,Hyundai,Elantra,2017,2.9,Electric,Automatic,38133,5,2,14837
22,Toyota,RAV4,2003,2.0,Electric,Manual,136662,5,4,6266
26,Audi,A3,2022,3.3,Electric,Manual,79350,5,3,14413
27,BMW,3 Series,2017,2.3,Electric,Semi-Automatic,142701,5,3,10645
...,...,...,...,...,...,...,...,...,...,...
9978,Mercedes,E-Class,2002,4.5,Diesel,Semi-Automatic,145363,5,2,6292
9979,Mercedes,C-Class,2012,4.3,Diesel,Automatic,51674,5,2,12466
9983,Mercedes,E-Class,2022,3.2,Petrol,Automatic,92823,5,4,13543
9991,Mercedes,E-Class,2017,1.1,Diesel,Automatic,179286,5,1,8214
9997,BMW,3 Series,2010,3.0,Petrol,Automatic,86664,5,1,9866

In [38]:
#15. What is the average mileage for each fuel type?
average_mileage_by_fuel = df.groupby("Fuel_Type")["Mileage"].mean()


print(average_mileage_by_fuel)

Fuel_Type
Diesel      150261.533041
Electric    151059.307429
Hybrid      145577.587036
Petrol      149917.694606
Name: Mileage, dtype: float64

In [39]:
#16. How many cars are from the brand 'Toyota'?
toyota = df[df["Brand"] == "Toyota"]

print(f"The number of Toyota cars is {len(toyota)}")

The number of Toyota cars is 970

In [41]:
#17. What is the average price of cars with automatic transmission?
automatic_transmission_cars = df[df['Transmission'] == 'Automatic']
average_price_automatic = automatic_transmission_cars['Price'].mean()
print(f"The average price of cars with automatic transmission is {average_price_automatic}")

The average price of cars with automatic transmission is 9938.252939403075

In [42]:
#18. Which car has the highest owner count?
highest_owner_car = df[df['Owner_Count'] == df['Owner_Count'].max()]['Model'].iloc[0]
print(f"The car with the highest owner count is {highest_owner_car}")

The car with the highest owner count is Rio

In [43]:
#19. What is the average engine size for cars with diesel fuel type?
diesel_cars = df[df['Fuel_Type'] == 'Diesel']
average_engine_size_diesel = diesel_cars['Engine_Size'].mean()
print(f"The average engine size for cars with diesel fuel type is {average_engine_size_diesel}")

The average engine size for cars with diesel fuel type is 3.011863057324841

In [44]:
#20. How many cars have a price greater than $10,000?
expensive_cars = df[df['Price'] > 10000]
print(f"The number of cars with a price greater than $10,000 is {len(expensive_cars)}")

The number of cars with a price greater than $10,000 is 3651